### ISSUE TITLE
Build error in arsnova.click

### ISSUE THREAD

**Issue by cuhkrain** [thm-projects/arsnova.click#1]
Dear Team,

I met a build error when i rebuild the source code. Seems it is caused by fiber.js 

The error picture: https://drive.google.com/file/d/1sdFRNOAs8VBhSWhoIvFTspkGtSxzaayU/view?usp=sharing

Could you kindly help advise which modules having problem and how to fix this? Following is the environment I am using:

OS: Win 7 64bit , also met this same problem on Ubuntu 17.10
Git: Git-2.16.2-64-bit
Mongodb: mongodb-win32-x86_64-2008plus-ssl-3.6.3
Nodejs: node-v8.10.0-x64
Meteor: 1.6.0.1

Many thanks for your kind help in advance!
Rain LI

**Comment by commana** [comment]
Thanks for reporting this issue! A fix for that has already been applied in the staging branch, but we are not yet ready to merge into master. If you feel like it, you may cherry-pick this commit, which may already help you: 

https://github.com/thm-projects/arsnova.click/commit/3b297a7fca481839656758b88ba6125026134aac

**Comment by knoxdj** [comment]
i'm newbie at this tools and really i need a help...this is a project from a coworker an i need to understand how this app works and where is the data repository because i need to export this json collection to another app...thanks a lot again...

**Comment by hafieyz** [comment]
im also having same issue..

**Comment by nsklyarov** [comment]
hey guys, you need fix simpl-schema on 1.4.1 version for resolve this issue

**Comment by nsklyarov** [comment]
this problem is also relevant

https://stackoverflow.com/questions/45620780/meteor-error-on-fast-rendering-path-typeerror-dynamics-slice-is-not-a-function

**Comment by nsklyarov** [comment]
and yes, thanks for the project, it's cool

**Comment by trayhem** [comment]
This is a question regarding the version 1 of arsnova.click which is now in legacy mode and not supported anymore. The version 2 is available either from git or docker if you don't want to build the app by yourself. 

https://git.thm.de/arsnova/arsnova-click-v2-frontend
https://git.thm.de/arsnova/arsnova-click-v2-backend
https://hub.docker.com/r/arsnova/arsnova-click-frontend
https://hub.docker.com/r/arsnova/arsnova-click-backend

See the dev wiki here: https://git.thm.de/arsnova/arsnova-click-v2/wikis/home
