### ISSUE TITLE
Creating a new question should immediately offer it for editing

### ISSUE THREAD

**Issue by ccoenen** [thm-projects/arsnova.click#11]
When I add a question and choose its type, I would directly go to the screen that lets me edit that question. (`quiz/manager/0/overview`)

I find it somewhat improbable that someone would _first_ create 5-10 empty question placeholders and then going over them to fill in the details. So going to the edit screen directly (perhaps even through to `/quiz/manager/0/questionText` !) would save a few clicks for every single question one creates.

**Comment by trayhem** [comment]
Fixed on https://staging.arsnova.click
