### ISSUE TITLE
Keyboard Shortcuts for question manager

### ISSUE THREAD

**Issue by ccoenen** [thm-projects/arsnova.click#13]
I would love to see keyboard shortcuts for the question manager. One thing I _constantly_ need is: going back from question text screen (or answeroptions screen) to the overview of a single question. I would like to propose mapping the <kbd>ESC</kbd> key to that.

Other nice shortcuts could be:
- <kbd>Ctrl</kbd>+<kbd>1</kbd>: create a new question of type Multiple choice
- ... (you get the idea!)
- <kbd>Ctrl</kbd>+<kbd>8</kbd>: create a new question of type Survey
- <kbd>Ctrl</kbd>+<kbd>Q</kbd>: edit a question's questionText (might conflict with system shortcuts on mac OS? not sure about this one)
- <kbd>Ctrl</kbd>+<kbd>A</kbd>: edit a question's answeroptions (wouldn't work while text field is in focus, but would be a nice shortcut nonetheless)
- <kbd>Ctrl</kbd>+<kbd>&larr;</kbd>: moving "sideways" to the previous question (so from `quiz/manager/4/overview` to `quiz/manager/3/overview` or also from `quiz/manager/4/questionText` to `quiz/manager/3/questionText` and so on for all the tabs)
- <kbd>Ctrl</kbd>+<kbd>&rarr;</kbd>: moving "sideways" to the next question (so from `quiz/manager/4/overview` to `quiz/manager/5/overview` or also from `quiz/manager/4/questionText` to `quiz/manager/5/questionText` and so on for all the tabs)

**Comment by trayhem** [comment]
Feel free to check out the early implementation on https://staging.arsnova.click

**Comment by ccoenen** [comment]
Oh that's nice :-)
This combined with jumping to a new question right away saves _so many_ switches between mouse and keyboard!

**Comment by ccoenen** [comment]
Now if there's two more shortcuts to jump to question and to answer (along with `.focus()` on the appropriate input element) one could enter whole quizzez without using a mouse :-) Great work so far!

**Comment by trayhem** [comment]
There are already shortcuts for switching to the question (ctrl + 1) or answers (ctrl + 2). I've added the autofocus to the question text view although I'll have to test it further on mobile devices. 

The autofocus in the answeroption view is not appropriate since there is either no answer at all yet (init state) or multiple answers (we cannot know which one should be selected). So there will be no option to enable the autofocus in the answeroption view.

**Comment by ccoenen** [comment]
nice, I didn't catch that :)

works very well so far!
