### ISSUE TITLE
arsnova.click production ready build documentation

### ISSUE THREAD

**Issue by stweiz** [thm-projects/arsnova.click#5]
Hi,

I want to use a production ready release of arsnova.click. So I take the master with the last commit of 19 Jul 2018 and build it with the following command:

`meteor build ../arsnova.click-build/production --server=<host>:443`

Then I take the built files and put them in a Docker image along with nodejs, npm etc. and start it 
with `node main.js` as you can see in this Dockerfile: https://gitlab.com/stevog/arsnova.click/blob/master/build_files/Dockerfile

Then I start a separate MongoDB and arsnova.click in a docker-compose context:
https://gitlab.com/stevog/arsnova.click/blob/master/build_files/docker-compose.yml

When everything is started, I only see a background with the connection check of this application. But everything else isn't loading and I get no errors in the browser console and the logs.

Starting the application with `meteor --settings settings.json` does work, but that's not what I want for production.

Thank you!

**Comment by trayhem** [comment]
This is regarding the v1 of arsnova.click which is now in legacy mode.  The build documentation of arsnova.click v2 can be found here: https://git.thm.de/arsnova/arsnova-click-v2/wikis/home
