### ISSUE TITLE
Quizmanager: list should show the question

### ISSUE THREAD

**Issue by ccoenen** [thm-projects/arsnova.click#7]
currently, it is not easy to structure your questions because the list just mentions the _type_ of question, but not the question:

![grafik](https://user-images.githubusercontent.com/124909/81021585-c2426f00-8e6b-11ea-8366-16eeb64b8c38.png)

I would like to suggest adding the question in place of question type (or at least in addition to the question type)

**Comment by ccoenen** [comment]
Unfortunately I can't comment on https://git.thm.de/arsnova/arsnova-click-v2/issues/89 directly, but I would like to point out that I _really_ can't work with this list like that. I have a 20 question quiz that I gave up on re-ordering, because it is simply too much work.

Having the question there is not visual noise, it is critical information for that list in particular. I would argue that the question is more important than the question type. Furthermore, the type could probably be hinted at by some icon if having _both_ as a text element would be too much.

![image](https://user-images.githubusercontent.com/124909/81350753-f5327000-90c2-11ea-9e2a-bf9a141ed9fc.png)

**Comment by trayhem** [comment]
Hi and thanks for clarification,
would something like this suit your needs?

![screencapture-localhost-4200-quiz-manager-overview-2020-05-08-10_31_16](https://user-images.githubusercontent.com/1389456/81387530-23da3600-9117-11ea-9366-67fd24cec197.png)

**Comment by trayhem** [comment]
Have a look at our testing environment (https://staging.arsnova.click) to check out the feature implementation

**Comment by ccoenen** [comment]
I have now used this successfully, and it is much nicer!
