### ISSUE TITLE
Quizmanager: "create new question button" misleading

### ISSUE THREAD

**Issue by ccoenen** [thm-projects/arsnova.click#8]
the button that lets you create a new question is not clearly labelled.
![grafik](https://user-images.githubusercontent.com/124909/81021681-ff0e6600-8e6b-11ea-992c-0b8232e36321.png)

It should simply read "new question" / "neue Frage". It should also be at the bottom of the list, and not above the headline. A "+" sign might also help.

**Comment by trayhem** [comment]
This should work now on https://arsnova.click

**Comment by ccoenen** [comment]
Yeah! This is very nice!
