### ISSUE TITLE
Quiz Flow: next question button is weirdly labelled and in the wrong place

### ISSUE THREAD

**Issue by ccoenen** [thm-projects/arsnova.click#9]
![grafik](https://user-images.githubusercontent.com/124909/81022239-637df500-8e6d-11ea-874b-1df114c0a38a.png)

This button (the orange "quiz starten" button) belongs over to the right, and it should be labelled "trigger next question" / "nächste Frage freigeben" or something similar.

**Comment by trayhem** [comment]
This should work now on https://arsnova.click

**Comment by ccoenen** [comment]
much better :-) thanks!
